# Generated by Django 4.1.1 on 2022-09-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_gender_alter_student_mail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='page_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
