# Generated by Django 4.1.1 on 2022-09-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_rename_phone_school_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='page_count',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='no_of_pages_read',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
