# Generated by Django 4.1.1 on 2022-09-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_remove_book_page_count_book_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='no_of_pages_read',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
