# Generated by Django 4.1.1 on 2022-09-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_student_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='books',
            field=models.ManyToManyField(blank=True, null=True, to='students.book'),
        ),
    ]
